Repository City-of-Helsinki/varaamo, pull requests merged in 2019-03, with the labels that each got.

#878 [Feature] Remove the link for old website from the footer
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
Labels: In R eview

#879 [Fix/Upgrade] Upgrade React to v15.6.2, Enzyme and other related dependencies.
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.spec.js
  app/shared/resource-card/ResourceCard.spec.js
  app/shared/resource-icons/ResourceIcons.spec.js
  config/specs.bootstrap.js
  package.json
  server/Html.js
Labels: In R eview

#889 Disable reservation time limit for admins
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.spec.js
Labels: Ready to merge

#902 Open new tab when click admin icons
  app/shared/main-navbar/MainNavbar.js
  app/shared/main-navbar/MainNavbar.spec.js
Labels: Ready to merge, enhancement

#903 Release 0.1.0
  CHANGELOG.md
  package.json
Labels: Ready to merge, enhancement
