Repository City-of-Helsinki/varaamo, pull requests merged in 2019-12, with the labels that each got.

#1078 VAR - 158 | My reservation history
  CHANGELOG.md
  app/actions/reservationActions.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/user-reservations/UserReservationsPage.js
  app/pages/user-reservations/__tests__/UserReservationsPage.test.js
  app/pages/user-reservations/__tests__/userReservationsPageSelector.test.js
  app/pages/user-reservations/reservation-list/ReservationListContainer.js
  app/pages/user-reservations/reservation-list/__tests__/ReservationListContainer.test.js
  app/pages/user-reservations/reservation-list/reservationListSelector.js
  app/pages/user-reservations/userReservationsPageSelector.js
  app/state/selectors/paginatedReservationsSelector.js
Labels: enhancement

#1080 Fix/var 256 event description required
  CHANGELOG.md
  app/constants/AppConstants.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/utils/__tests__/reservationUtils.test.js
Labels: bug

#1081 VAR - 251 | Include billing fields in modals.
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/reservation/ReservationPage.js
  app/shared/modals/reservation-info/ReservationEditForm.js
  src/domain/reservation/manage/page/ManageReservationsPage.js
  src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
  src/domain/reservation/modal/ReservationInformationModal.js
Labels: enhancement

#1082 Switched resource specificTerms position on view.
  CHANGELOG.md
  app/pages/reservation/reservation-information/ReservationInformationForm.js
Labels: enhancement

#1083 VAR - 257 | Reorder and combine blocks
  CHANGELOG.md
  app/pages/resource/ResourcePage.js
  app/pages/resource/reservation-info/ReservationInfo.js
  app/pages/resource/reservation-info/__tests__/ReservationInfo.test.js
  app/pages/resource/resource-info/ResourceInfo.js
Labels: enhancement

#1084 VAR - 249 | Update footer version
  package.json
  src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
Labels: enhancement

#1086 Release 0.8.0
  CHANGELOG.md
Labels: enhancement

#1087 VAR - 198 | Wrong view after editing reservation
  CHANGELOG.md
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-confirmation/ReservationConfirmation.js
  app/pages/reservation/reservation-confirmation/__tests__/ReservationConfirmation.test.js
  app/pages/reservation/reservation-information/InternalReservationFields.js
  src/domain/reservation/manage/page/ManageReservationsPage.js
Labels: bug, enhancement

#1088 VAR - 213 | Search page dropdown & time range
  CHANGELOG.md
  src/domain/search/filters/filter/SelectFilter.js
  src/domain/search/filters/filter/TimeRangeFilter.js
  src/domain/search/filters/filter/__tests__/__snapshots__/TimeRangeFilter.test.js.snap
  src/domain/search/filters/filter/_timeRangeFilter.scss
  src/domain/search/results/_searchListResults.scss
Labels: bug

#1089 VAR - 37 | Today buttons
  CHANGELOG.md
  app/shared/availability-view/DateSelector.js
  app/shared/availability-view/_availability-view.scss
  src/domain/search/filters/SearchFilters.js
  src/domain/search/filters/__tests__/__snapshots__/SearchFilters.test.js.snap
  src/domain/search/filters/_searchFilters.scss
  src/domain/search/filters/filter/_dateFilter.scss
Labels: enhancement

#1091 VAR - 218 | Show how many days before user can make reservation
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/resource/ResourcePage.js
  app/pages/resource/__tests__/ResourcePage.test.js
  app/pages/resource/reservation-info/ReservationInfo.js
  app/pages/resource/reservation-info/__tests__/ReservationInfo.test.js
  app/pages/resource/resource-info/ResourceInfo.js
  app/shared/resource-calendar/ResourceCalendar.js
  app/shared/resource-calendar/__tests__/ResourceCalendar.test.js
Labels: enhancement

#1092 VAR - 256 | Wrong mandatory field
  CHANGELOG.md
  app/constants/AppConstants.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/pages/reservation/reservation-information/Textarea.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformationForm.test.js
  app/shared/form-fields/TermsField.js
  app/utils/__tests__/reservationUtils.test.js
Labels: bug, enhancement

#1093 Release 0.8.1
  CHANGELOG.md
  app/constants/AppConstants.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-confirmation/ReservationConfirmation.js
  app/pages/reservation/reservation-confirmation/__tests__/ReservationConfirmation.test.js
  app/pages/reservation/reservation-information/InternalReservationFields.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/pages/reservation/reservation-information/Textarea.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformationForm.test.js
  app/pages/resource/ResourcePage.js
  app/pages/resource/__tests__/ResourcePage.test.js
  app/pages/resource/reservation-info/ReservationInfo.js
  app/pages/resource/reservation-info/__tests__/ReservationInfo.test.js
  app/pages/resource/resource-info/ResourceInfo.js
  app/shared/availability-view/DateSelector.js
  app/shared/availability-view/_availability-view.scss
  app/shared/form-fields/TermsField.js
  app/shared/resource-calendar/ResourceCalendar.js
  app/shared/resource-calendar/__tests__/ResourceCalendar.test.js
  app/utils/__tests__/reservationUtils.test.js
  package.json
  src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
  src/domain/reservation/manage/page/ManageReservationsPage.js
  src/domain/search/filters/SearchFilters.js
  src/domain/search/filters/__tests__/__snapshots__/SearchFilters.test.js.snap
  src/domain/search/filters/_searchFilters.scss
  src/domain/search/filters/filter/SelectFilter.js
  src/domain/search/filters/filter/TimeRangeFilter.js
  src/domain/search/filters/filter/__tests__/__snapshots__/TimeRangeFilter.test.js.snap
  src/domain/search/filters/filter/_dateFilter.scss
  src/domain/search/filters/filter/_timeRangeFilter.scss
  src/domain/search/results/_searchListResults.scss
Labels: enhancement

#1094 Release/0.8.1
  CHANGELOG.md
  package.json
  src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
Labels: enhancement

#1095 Feature/var 234 display extra question field on reservation form
  CHANGELOG.md
  app/actions/uiActions.js
  app/constants/ActionTypes.js
  app/constants/AppConstants.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/admin-resources/AdminResourcesPage.js
  app/pages/admin-resources/__tests__/AdminResourcesPage.test.js
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-information/InternalReservationFields.js
  app/pages/reservation/reservation-information/ReservationInformation.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/shared/modals/reservation-info/ReservationEditForm.js
  app/state/reducers/ui/reservationsReducer.js
  app/utils/__tests__/reservationUtils.test.js
  src/common/data/utils.js
Labels: enhancement

#1096 Added ResourcePanel for genericTerms. Added new translations too.
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/reservation/reservation-information/Textarea.js
  app/pages/resource/resource-info/ResourceInfo.js
  package.json
  yarn.lock
Labels: enhancement

#1098 Feature/var 235 user notificator
  .env.example
  CHANGELOG.md
  app/pages/AppContainer.js
  app/shared/modals/reservation-info/ReservationEditForm.js
  config/webpack.common.js
  docs/FIREBASE.md
  docs/NOTIFICATOR.md
  package.json
  src/common/_common.scss
  src/common/notificator/create/CreateNotifications.js
  src/common/notificator/create/__tests__/CreateNotifications.test.js
  src/common/notificator/create/__tests__/__snapshots__/CreateNotifications.test.js.snap
  src/common/notificator/create/_createNotifications.scss
  src/common/notificator/create/form/CreateNotificationsForm.js
  src/common/notificator/create/form/__tests__/CreateNotificationsForm.test.js
  src/common/notificator/create/form/__tests__/__snapshots__/CreateNotificationsForm.test.js.snap
  src/common/notificator/create/list/CreateNotificationsList.js
  src/common/notificator/create/list/__tests__/CreateNotificationsList.test.js
  src/common/notificator/create/list/__tests__/__snapshots__/CreateNotificationsList.test.js.snap
  src/common/notificator/create/modal/CreateNotificationModal.js
  src/common/notificator/create/modal/DeleteConfirmationModal.js
  src/common/notificator/create/modal/__tests__/CreateNotificationsModal.test.js
  src/common/notificator/create/modal/__tests__/__snapshots__/CreateNotificationsModal.test.js.snap
  src/common/notificator/date/NotificatorDatePicker.js
  src/common/notificator/date/_notificationDatePicker.scss
  src/common/notificator/user/UserNotificator.js
  src/common/notificator/user/__tests__/UserNotificator.test.js
  src/common/notificator/user/_userNotificator.scss
  src/common/notificator/utils.js
  src/domain/search/filters/filter/TimeRangeFilter.js
  src/index.js
  src/routes.js
  yarn.lock
Labels: enhancement
