Repository City-of-Helsinki/varaamo, pull requests merged in 2019-11, with the labels that each got.

#1052 VAR-160 | VAR-161 | Add internal field for staff in ReservationForm
  .gitignore
  CHANGELOG.md
  app/assets/styles/_modals.scss
  app/constants/FormTypes.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/__tests__/ReservationPage.test.js
  app/pages/reservation/reservation-information/InternalReservationFields.js
  app/pages/reservation/reservation-information/ReservationInformation.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformation.test.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformationForm.test.js
  app/pages/reservation/reservation-information/_reservation-information.scss
  app/shared/reservation-confirmation/ConfirmReservationModal.js
  app/shared/reservation-confirmation/ReservationForm.js
  app/shared/reservation-confirmation/__tests__/ConfirmReservationModal.test.js
  app/shared/reservation-confirmation/__tests__/ReservationForm.test.js
Labels: enhancement

#1057 Update develop from master
  CHANGELOG.md
  app/pages/reservation/ReservationPage.js
  app/pages/resource/ResourcePage.js
  app/pages/resource/__tests__/ResourcePage.test.js
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/domain/search/page/SearchPage.js
Labels: bug

#1058 VAR-161 | Staff event checkbox for staff
  CHANGELOG.md
  app/pages/reservation/reservation-information/InternalReservationFields.js
  src/domain/reservation/constants.js
Labels: enhancement

#1059 VAR-224 | Cant change week when editing reservation
  CHANGELOG.md
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-time/ReservationTime.js
  app/pages/reservation/reservation-time/__tests__/ReservationTime.test.js
  app/shared/resource-calendar/ResourceCalendar.js
  app/shared/resource-calendar/__tests__/ResourceCalendar.test.js
  app/shared/resource-calendar/_resource-calendar.scss
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
Labels: bug

#1060 VAR-216 | Resourcepage scrollbars
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/resource/resource-info/ResourceInfo.js
  app/pages/resource/resource-info/_resource-info.scss
Labels: bug

#1061 VAR- 224 | Can't change week.
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/resource/ResourcePage.js
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
Labels: bug

#1062 Bug/var 223 notifications missing
  CHANGELOG.md
  app/actions/notificationsActions.js
  app/pages/AppContainer.js
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-time/ReservationTime.js
  app/pages/reservation/reservation-time/__tests__/ReservationTime.test.js
  app/pages/resource/ResourcePage.js
  app/shared/notifications/NotificationsContainer.js
  app/shared/notifications/__tests__/NotificationsContainer.test.js
  app/state/reducers/__tests__/notificationsReducer.test.js
  app/state/reducers/notificationsReducer.js
  app/state/rootReducer.js
  src/common/api/client.js
Labels: bug

#1063 Increased z-index value.
  CHANGELOG.md
  src/common/form/fields/_dateField.scss
Labels: bug

#1064 Replaced ? with & in Feedback URL.
  CHANGELOG.md
  app/pages/reservation/reservation-confirmation/ReservationConfirmation.js
Labels: bug

#1065 Replaced some frontpage icons.
  CHANGELOG.md
  src/domain/home/HomePage.js
  src/domain/home/images/frontpage_event.svg
  src/domain/home/images/frontpage_guidance.svg
  src/domain/home/images/frontpage_sauna.svg
Labels: enhancement

#1066 Minor change in ReservationInformationModal reservation data structure.
  CHANGELOG.md
  src/domain/reservation/modal/ReservationInformationModal.js
Labels: enhancement

#1067 VAR-162 | Mobile version improvement for fullcalendar.
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/resource/ResourcePage.js
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
Labels: enhancement

#1068 Release 0.7.0
  .gitignore
  CHANGELOG.md
  app/actions/notificationsActions.js
  app/assets/styles/_modals.scss
  app/constants/FormTypes.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/AppContainer.js
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/__tests__/ReservationPage.test.js
  app/pages/reservation/reservation-confirmation/ReservationConfirmation.js
  app/pages/reservation/reservation-information/InternalReservationFields.js
  app/pages/reservation/reservation-information/ReservationInformation.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformation.test.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformationForm.test.js
  app/pages/reservation/reservation-information/_reservation-information.scss
  app/pages/reservation/reservation-time/ReservationTime.js
  app/pages/reservation/reservation-time/__tests__/ReservationTime.test.js
  app/pages/resource/ResourcePage.js
  app/pages/resource/resource-info/ResourceInfo.js
  app/pages/resource/resource-info/_resource-info.scss
  app/shared/notifications/NotificationsContainer.js
  app/shared/notifications/__tests__/NotificationsContainer.test.js
  app/shared/reservation-confirmation/ConfirmReservationModal.js
  app/shared/reservation-confirmation/ReservationForm.js
  app/shared/reservation-confirmation/__tests__/ConfirmReservationModal.test.js
  app/shared/reservation-confirmation/__tests__/ReservationForm.test.js
  app/shared/resource-calendar/ResourceCalendar.js
  app/shared/resource-calendar/__tests__/ResourceCalendar.test.js
  app/shared/resource-calendar/_resource-calendar.scss
  app/state/reducers/__tests__/notificationsReducer.test.js
  app/state/reducers/notificationsReducer.js
  app/state/rootReducer.js
  src/common/api/client.js
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
  src/common/form/fields/_dateField.scss
  src/domain/home/HomePage.js
  src/domain/home/images/frontpage_event.svg
  src/domain/home/images/frontpage_guidance.svg
  src/domain/home/images/frontpage_sauna.svg
  src/domain/reservation/constants.js
  src/domain/reservation/modal/ReservationInformationModal.js
Labels: enhancement

#1069 Merge release to develop 0.7.0
  CHANGELOG.md
Labels: enhancement

#1070 Feature/var 236 add first name last name email phone number to payment form
  CHANGELOG.md
  app/pages/reservation/reservation-information/ReservationInformation.js
Labels: enhancement

#1071 VAR - 128 | My premises payment info
  CHANGELOG.md
  app/constants/AppConstants.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/shared/availability-view/_availability-view.scss
  app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/AvailabilityTimeline.js
  app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/Reservation.js
  app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/__tests__/AvailabilityTimeline.test.js
  app/shared/modals/reservation-info/ReservationEditForm.js
  app/shared/modals/reservation-info/ReservationInfoModal.js
  app/shared/modals/reservation-info/__tests__/ReservationInfoModal.test.js
  app/shared/modals/reservation-info/_reservation-info-modal.scss
  src/common/_common.scss
  src/common/label/InfoLabel.js
  src/common/label/__tests__/InfoLabel.test.js
  src/common/label/__tests__/__snapshots__/InfoLabel.test.js.snap
  src/common/label/_infoLabel.scss
  src/domain/resource/utils.js
Labels: enhancement

#1072 VAR - 127 | My reservation payment info
  CHANGELOG.md
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/pages/user-reservations/reservation-list/ReservationListItem.js
  app/pages/user-reservations/reservation-list/__tests__/ReservationListItem.test.js
  app/pages/user-reservations/reservation-list/_reservation-list.scss
  app/shared/modals/reservation-cancel/reservationCancelModalSelector.js
  app/shared/modals/reservation-info/ReservationEditForm.js
  app/shared/reservation-controls/ReservationControls.js
  app/shared/reservation-controls/ReservationControlsContainer.js
  src/common/label/_infoLabel.scss
Labels: enhancement

#1073 VAR - 238 | Change min slot size in my premises
  CHANGELOG.md
  app/shared/availability-view/_availability-view.scss
  app/shared/availability-view/timeline-groups/timeline-group/TimelineGroup.js
  app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/AvailabilityTimeline.js
  app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/ReservationSlot.js
  app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/__tests__/ReservationSlot.test.js
Labels: enhancement

#1074 VAR - 237 | Display payment and resource terms of service
  CHANGELOG.md
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-information/ReservationInformation.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformation.test.js
  app/pages/reservation/reservation-information/_reservation-information.scss
  app/shared/form-fields/TermsField.js
  app/shared/form-fields/__tests__/TermsField.test.js
Labels: enhancement

#1075 VAR - 253 | Display premise location text in my premises page
  CHANGELOG.md
  app/pages/admin-resources/AdminResourcesPage.js
  app/pages/admin-resources/__tests__/AdminResourcesPage.test.js
  app/pages/admin-resources/__tests__/adminResourcesPageSelector.test.js
  app/pages/admin-resources/adminResourcesPageSelector.js
  app/shared/availability-view/_availability-view.scss
  app/shared/availability-view/sidebar/group-info/resource-info/ResourceInfoContainer.js
  app/shared/availability-view/sidebar/group-info/resource-info/__tests__/ResourceInfoContainer.test.js
Labels: enhancement

#1076 VAR - 246 | Display legend information reservation calendar
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  src/common/_common.scss
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
  src/common/calendar/legend/CalendarLegend.js
  src/common/calendar/legend/__tests__/CalendarLegend.test.js
  src/common/calendar/legend/__tests__/__snapshots__/CalendarLegend.test.js.snap
  src/common/calendar/legend/_calendarLegend.scss
Labels: enhancement

#1077 VAR - 255 | Manage reservations finnish translations
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/reservation/reservation-information/ReservationInformation.js
  app/pages/reservation/reservation-information/ReservationInformationForm.js
  app/pages/reservation/reservation-information/__tests__/ReservationInformationForm.test.js
  src/common/calendar/legend/_calendarLegend.scss
Labels: bug, enhancement
