Repository City-of-Helsinki/varaamo, pull requests merged in 2019-05, with the labels that each got.

#924 VAR-50 | Add municipality to clear filter list.
  app/constants/AppConstants.js
  app/pages/search/controls/SearchControlsContainer.js
  app/shared/resource-map/mapSelector.js
  app/state/reducers/ui/searchReducer.js
  app/state/reducers/ui/searchReducer.spec.js
  app/state/selectors/__tests__/uiSearchFiltersSelector.spec.js
  app/state/selectors/__tests__/urlSearchFiltersSelector.spec.js
Labels: enhancement

#925 VAR-57 | Add slot_size and minPeriod to reservation select
  app/constants/SlotConstants.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/resource/ResourcePage.js
  app/pages/resource/reservation-calendar/reservationCalendarSelector.js
  app/pages/resource/reservation-calendar/reservationCalendarSelector.spec.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlot.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlot.spec.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.spec.js
  app/pages/resource/reservation-calendar/utils.js
  app/pages/resource/reservation-calendar/utils.spec.js
  app/shared/form-fields/ReservationTimeControls.js
  app/shared/modals/reservation-info/ReservationEditForm.js
  app/shared/reservation-controls/ReservationControlsContainer.js
  app/shared/reservation-controls/ReservationControlsContainer.spec.js
  app/shared/resource-calendar/resourceCalendarSelector.spec.js
  app/state/reducers/ui/reservationsReducer.js
  app/state/reducers/ui/reservationsReducer.spec.js
  app/utils/__tests__/resourceUtils.spec.js
  app/utils/__tests__/timeUtils.spec.js
  app/utils/fixtures/Resource.js
  app/utils/resourceUtils.js
  app/utils/timeUtils.js
Labels: enhancement

#927 VAR-51 | Translate SelectControl noOptionsMessage
  .gitignore
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/search/controls/SelectControl.js
  app/pages/search/controls/SelectControl.spec.js
Labels: enhancement

#928 VAR-76 | Fix the bug of getting one slot extra in timediff.
  app/pages/resource/reservation-calendar/time-slots/TimeSlot.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlot.spec.js
  app/state/reducers/ui/reservationsReducer.js
  app/state/reducers/ui/reservationsReducer.spec.js
  app/utils/timeUtils.js
Labels: bug

#930 VAR-73 | show warning when select disabled slot by mistake
  app/pages/resource/reservation-calendar/ReservationCalendarContainer.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlot.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
  app/pages/resource/reservation-calendar/utils.js
  app/pages/resource/reservation-calendar/utils.spec.js
Labels: bug

#931 VAR-73 | disable isUnderMinPeriod check anytime there are selected slot
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
Labels: bug

#933 Release 0.3.0
  .env.example
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  app/constants/AppConstants.js
  app/constants/SlotConstants.js
  app/i18n/changeLocale.js
  app/i18n/initI18n.js
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/resource/ResourcePage.js
  app/pages/resource/reservation-calendar/ReservationCalendarContainer.js
  app/pages/resource/reservation-calendar/reservationCalendarSelector.js
  app/pages/resource/reservation-calendar/reservationCalendarSelector.spec.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlot.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlot.spec.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.spec.js
  app/pages/resource/reservation-calendar/utils.js
  app/pages/resource/reservation-calendar/utils.spec.js
  app/pages/search/controls/SearchControlsContainer.js
  app/pages/search/controls/SearchControlsContainer.spec.js
  app/pages/search/controls/SelectControl.js
  app/pages/search/controls/SelectControl.spec.js
  app/pages/user-reservations/reservation-list/ReservationListItem.js
  app/shared/date-picker/DatePicker.js
  app/shared/date-picker/DatePicker.spec.js
  app/shared/form-fields/ReservationTimeControls.js
  app/shared/modals/reservation-info/ReservationEditForm.js
  app/shared/modals/reservation-success/ReservationSuccessModal.js
  app/shared/reservation-access-code/GeneratedAccessCode.js
  app/shared/reservation-access-code/GeneratedAccessCode.spec.js
  app/shared/reservation-access-code/PendingAccessCode.js
  app/shared/reservation-access-code/PendingAccessCode.spec.js
  app/shared/reservation-access-code/ReservationAccessCode.js
  app/shared/reservation-access-code/ReservationAccessCode.spec.js
  app/shared/reservation-access-code/helpers.js
  app/shared/reservation-controls/ReservationControlsContainer.js
  app/shared/reservation-controls/ReservationControlsContainer.spec.js
  app/shared/resource-calendar/resourceCalendarSelector.spec.js
  app/shared/resource-card/info/ResourceCardInfoCell.spec.js
  app/shared/resource-map/mapSelector.js
  app/state/reducers/ui/reservationsReducer.js
  app/state/reducers/ui/reservationsReducer.spec.js
  app/state/reducers/ui/searchReducer.js
  app/state/reducers/ui/searchReducer.spec.js
  app/state/selectors/__tests__/uiSearchFiltersSelector.spec.js
  app/state/selectors/__tests__/urlSearchFiltersSelector.spec.js
  app/utils/__tests__/resourceUtils.spec.js
  app/utils/__tests__/timeUtils.spec.js
  app/utils/fixtures/Resource.js
  app/utils/resourceUtils.js
  app/utils/timeUtils.js
  config/jest/setupJest.js
  config/webpack.development.js
  config/webpack.production.js
  package.json
  yarn.lock
Labels: enhancement

#935 Update develop with 0.3.0 release
  CHANGELOG.md
  package.json
Labels: Ready to merge

#940 VAR-82 | VAR-80 | VAR-81 | Upgrade fortawesome, add new temp purpose icon
  app/pages/home/HomePage.js
  app/pages/home/_home-page.scss
  package.json
  yarn.lock
Labels: enhancement

#942 Release v0.4.0
  .eslintrc
  CHANGELOG.md
  app/pages/PageWrapper.js
  app/pages/home/HomePage.js
  app/pages/home/_home-page.scss
  app/pages/resource/ResourcePage.js
  app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
  app/pages/search/controls/CheckboxControl.js
  app/pages/search/results/SearchResultsPaging.js
  app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.js
  app/shared/favorite-button/FavoriteButton.js
  app/shared/label/Label.js
  app/shared/resource-card/ResourceCard.js
  app/shared/resource-map/MapContainer.js
  app/shared/resource-type-filter/ResourceTypeFilterButton.js
  config/webpack.development.js
  config/webpack.production.js
  package.json
  src/common/.empty
  src/domain/.empty
  src/index.js
  src/routes.js
  yarn.lock
Labels: Ready to merge, enhancement
