Repository City-of-Helsinki/varaamo, pull requests merged in 2019-10, with the labels that each got.

#1032 VAR-183 | Better max period handling for FullCalendar
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/__tests__/AppContainer.test.js
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/__tests__/utils.test.js
  src/common/calendar/utils.js
  src/domain/resource/__tests__/utils.test.js
  src/domain/resource/utils.js
Labels: bug, enhancement

#1034 Fix eslint for windows
  app/pages/browser-warning/BrowserWarning.js
  app/shared/form-fields/TermsField.js
  app/shared/modals/reservation-info/ReservationInfoModal.js
  app/shared/reservation-popover/ReservationPopover.js
Labels: enhancement

#1033 VAR-209 | Show errors to staff members if editing of reservations fail
  CHANGELOG.md
  src/common/api/client.js
  src/domain/reservation/manage/page/ManageReservationsPage.js
Labels: enhancement

#1031 VAR-173 | Use resource's userPermissions.isAdmin flag to check if user isStaff
  CHANGELOG.md
  app/pages/user-reservations/reservation-list/__tests__/reservationListSelector.test.js
  app/pages/user-reservations/reservation-list/reservationListSelector.js
  app/state/selectors/__tests__/authSelectors.test.js
  app/state/selectors/authSelectors.js
Labels: enhancement

#1035 VAR-205 | Daily/ Weekly view for mobile
  CHANGELOG.md
  app/pages/reservation/reservation-information/__tests__/ReservationInformation.test.js
  app/pages/resource/_resource-page.scss
  app/pages/resource/resource-header/_resource-header.scss
  app/pages/resource/resource-info/_resource-info.scss
  app/shared/resource-calendar/_resource-calendar.scss
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
Labels: enhancement

#1037 VAR-206 | Allow to select timeslot which is already happening
  CHANGELOG.md
  src/common/calendar/TimePickerCalendar.js
  src/domain/resource/utils.js
Labels: bug, enhancement

#1039 VAR-39 | Re-assign default timezone which was removed by fullcalendar moment-timezone
  CHANGELOG.md
  src/common/calendar/TimePickerCalendar.js
Labels: bug

#1036 VAR-207 | Refactoring notification code
  app/actions/notificationsActions.js
  app/shared/notifications/NotificationsContainer.js
  app/shared/notifications/__tests__/NotificationsContainer.test.js
  app/state/reducers/__tests__/notificationsReducer.test.js
  app/state/reducers/notificationsReducer.js
  app/state/rootReducer.js
  src/common/notification/utils.js
Labels: enhancement

#1038 Make sure that errors from Respa are actually shown to staff
  src/common/api/client.js
  src/domain/reservation/manage/page/ManageReservationsPage.js
Labels: bug

#1040 Adjustment value so calendar work better on mobile
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
Labels: enhancement

#1042 Release v0.6.0
  CHANGELOG.md
  package.json
  src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
Labels: Ready to merge, bug, enhancement

#1044 [Hotfix] VAR-149 | Populate resource fetching with default time range as 1 month.
  CHANGELOG.md
  package.json
  src/common/api/client.js
  src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
  src/domain/reservation/manage/page/__tests__/ManageReservationsPage.test.js
  src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
  src/domain/search/__tests__/utils.test.js
  src/domain/search/page/SearchPage.js
  src/domain/search/page/__tests__/SearchPage.test.js
  src/domain/search/page/__tests__/__snapshots__/SearchPage.test.js.snap
  src/domain/search/utils.js
  yarn.lock
Labels: bug

#1045 [Hotfix] VAR-149 | Merge hotfix back to develop
  CHANGELOG.md
  package.json
  src/common/api/client.js
  src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
  src/domain/reservation/manage/page/__tests__/ManageReservationsPage.test.js
  src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
  src/domain/search/__tests__/utils.test.js
  src/domain/search/page/SearchPage.js
  src/domain/search/page/__tests__/SearchPage.test.js
  src/domain/search/page/__tests__/__snapshots__/SearchPage.test.js.snap
  src/domain/search/utils.js
  yarn.lock
Labels: bug

#1046 [Hotfix] Reduce Varaamo unit, resource fetchAll page_size and timerange
  CHANGELOG.md
  src/domain/search/page/SearchPage.js
Labels: bug, enhancement

#1047 [Hotfix] Reduce payload - merge back to develop
  CHANGELOG.md
  src/domain/search/page/SearchPage.js
Labels: bug, enhancement

#1048 reduce payload from 4 month to 2 for single resource, 7 day to 1 day
  CHANGELOG.md
  app/pages/reservation/ReservationPage.js
  app/pages/resource/ResourcePage.js
  app/pages/resource/__tests__/ResourcePage.test.js
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/domain/search/page/SearchPage.js
Labels: bug
