Repository City-of-Helsinki/varaamo, pull requests merged in 2019-09, with the labels that each got.

#999 VAR-178 | Create reusable FullCalendar component
  CHANGELOG.md
  app/i18n/injectT.js
  app/shared/reservation-access-code/__tests__/ReservationAccessCode.test.js
  src/common/_common.scss
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/TimePickerCalendar.test.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/_timePickerCalendar.scss
  src/domain/reservation/manage/action/ManageReservationsDropdown.js
  src/domain/reservation/manage/action/__tests__/ManageReservationsDropdown.test.js
  src/domain/reservation/manage/action/__tests__/__snapshots__/ManageReservationsDropdown.test.js.snap
  src/domain/reservation/manage/list/__tests__/__snapshots__/ManageReservationsList.test.js.snap
  src/domain/resource/reservationCalendar/ResourceReservationCalendar.js
  src/domain/resource/reservationCalendar/__tests__/ResourceReservationCalendar.test.js
  src/domain/resource/reservationCalendar/__tests__/__snapshots__/ResourceReservationCalendar.test.js.snap
  src/domain/resource/reservationCalendar/_resourceReservationCalendar.scss
  src/domain/search/results/__tests__/__snapshots__/SearchListResults.test.js.snap
  src/domain/search/sort/SearchSort.js
  src/domain/search/sort/__tests__/SearchSort.test.js
  src/domain/search/sort/__tests__/__snapshots__/SearchSort.test.js.snap
Labels: enhancement

#1001 Refactor headers from app to src
  app/pages/AppContainer.js
  app/pages/__tests__/AppContainer.test.js
  app/shared/_shared.scss
  src/domain/header/Header.js
  src/domain/header/MainNavbar.js
  src/domain/header/MainNavbarContainer.js
  src/domain/header/TopNavbar.js
  src/domain/header/TopNavbarContainer.js
  src/domain/header/__tests__/Header.test.js
  src/domain/header/__tests__/MainNavbar.test.js
  src/domain/header/__tests__/MainNavbarContainer.test.js
  src/domain/header/__tests__/TopNavbar.test.js
  src/domain/header/__tests__/TopNavbarContainer.test.js
  src/domain/header/_header.scss
  src/domain/header/_main-navbar.scss
  src/domain/header/_top-navbar.scss
Labels: enhancement

#1002 VAR-179 | Replace failure message and add a return button
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/reservation/PaymentFailed.js
  app/pages/reservation/ReservationPaymentReturnPage.js
  app/pages/reservation/_reservation-page.scss
  src/common/form/fields/__tests__/__snapshots__/DateField.test.js.snap
  src/domain/search/filters/filter/__tests__/__snapshots__/DateFilter.test.js.snap
Labels: enhancement

#1003 Refactoring: Move footer from app/shared to src/domain
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/pages/AppContainer.js
  app/shared/_shared.scss
  app/shared/footer/Footer.js
  app/shared/footer/FooterContent.js
  app/shared/footer/__tests__/Footer.test.js
  app/shared/footer/__tests__/FooterContent.test.js
  src/domain/footer/Footer.js
  src/domain/footer/__tests__/Footer.test.js
  src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
  src/domain/footer/_footer.scss
Labels: enhancement

#1004 VAR-164 | Staff cannot see normal reservations
  CHANGELOG.md
  src/common/data/fixtures/reservation.js
  src/domain/reservation/__tests__/utils.test.js
  src/domain/reservation/manage/action/ManageReservationsDropdown.js
  src/domain/reservation/manage/action/__tests__/__snapshots__/ManageReservationsDropdown.test.js.snap
  src/domain/reservation/manage/list/ManageReservationsList.js
  src/domain/reservation/manage/list/__tests__/__snapshots__/ManageReservationsList.test.js.snap
  src/domain/reservation/manage/page/ManageReservationsPage.js
  src/domain/reservation/modal/ReservationInformationModal.js
  src/domain/reservation/modal/__tests__/__snapshots__/ReservationInfomationModal.test.js.snap
  src/domain/reservation/utils.js
Labels: bug, enhancement

#1005 VAR-181 | Reservation information modal is missing metadata fields
  CHANGELOG.md
  src/domain/reservation/constants.js
  src/domain/reservation/information/ReservationMetadata.js
  src/domain/reservation/information/__tests__/ReservationMetadata.test.js
  src/domain/reservation/information/__tests__/__snapshots__/ReservationMetadata.test.js.snap
  src/domain/reservation/manage/action/ManageReservationsDropdown.js
  src/domain/reservation/manage/action/__tests__/ManageReservationsDropdown.test.js
  src/domain/reservation/manage/action/__tests__/__snapshots__/ManageReservationsDropdown.test.js.snap
  src/domain/reservation/modal/ReservationInformationModal.js
  src/domain/reservation/modal/__tests__/__snapshots__/ReservationInfomationModal.test.js.snap
Labels: bug, enhancement

#1006 VAR-163 | Manage reservation filter buttons
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  app/state/selectors/dataSelectors.js
  src/common/form/fields/__tests__/__snapshots__/DateField.test.js.snap
  src/common/form/fields/_dateField.scss
  src/domain/reservation/constants.js
  src/domain/reservation/manage/filters/ManageReservationsFilters.js
  src/domain/reservation/manage/filters/__tests__/__snapshots__/ManageReservationsFilters.test.js.snap
  src/domain/reservation/manage/page/ManageReservationsPage.js
  src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
  src/domain/search/filters/filter/__tests__/__snapshots__/DateFilter.test.js.snap
Labels: enhancement

#1007 VAR-181 | Add missing metadata fields translations
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  src/common/form/fields/DateField.js
  src/common/form/fields/__tests__/DateField.test.js
  src/common/form/fields/__tests__/__snapshots__/DateField.test.js.snap
  src/domain/reservation/constants.js
  src/domain/reservation/manage/filters/__tests__/__snapshots__/ManageReservationsFilters.test.js.snap
  src/domain/search/filters/__tests__/__snapshots__/SearchFilters.test.js.snap
  src/domain/search/filters/filter/DateFilter.js
  src/domain/search/filters/filter/__tests__/DateFilter.test.js
  src/domain/search/filters/filter/__tests__/__snapshots__/DateFilter.test.js.snap
Labels: enhancement

#1008 VAR-163 | Add new filters to filter reset button, keep filter state when navigate.
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  src/common/form/fields/_buttonGroupField.scss
  src/domain/reservation/manage/filters/ManageReservationsFilters.js
  src/domain/reservation/manage/filters/__tests__/__snapshots__/ManageReservationsFilters.test.js.snap
  src/domain/reservation/manage/list/ManageReservationsList.js
  src/domain/reservation/manage/list/__tests__/__snapshots__/ManageReservationsList.test.js.snap
  src/domain/reservation/manage/page/ManageReservationsPage.js
  src/domain/reservation/manage/page/__tests__/ManageReservationsPage.test.js
  src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
Labels: enhancement

#1009 VAR-163 | Reset button display state when filter reset
  src/domain/reservation/manage/filters/ManageReservationsFilters.js
Labels: bug

#1010 VAR-172 | Full Calendar on Reservation page
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-time/ReservationTime.js
  app/pages/reservation/reservation-time/__tests__/ReservationTime.test.js
  app/state/reducers/ui/reservationsReducer.js
Labels: enhancement

#1011 VAR-192 | Add can_modify as default of `show_only` filter
  CHANGELOG.md
  src/domain/reservation/manage/page/ManageReservationsPage.js
  src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
Labels: enhancement

#1019 VAR-191 | Wrap empty value cell with -
  src/domain/reservation/manage/list/ManageReservationsList.js
  src/domain/reservation/manage/list/__tests__/__snapshots__/ManageReservationsList.test.js.snap
  src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
Labels: enhancement

#1022 VAR-197 | Move AboutPage to src
  app/pages/_pages.scss
  app/pages/about/AboutPage.js
  app/pages/about/AboutPageContent.js
  app/pages/about/__tests__/AboutPage.test.js
  app/pages/about/__tests__/AboutPageContent.test.js
  src/domain/_domain.scss
  src/domain/about/AboutPage.js
  src/domain/about/AboutPartners.js
  src/domain/about/__tests__/AboutPage.test.js
  src/domain/about/__tests__/AboutPartners.test.js
  src/domain/about/__tests__/__snapshots__/AboutPage.test.js.snap
  src/domain/about/_about-page.scss
  src/domain/about/images/aika-logo.png
  src/domain/about/images/eakr-logo.png
  src/domain/about/images/eu-vipuvoimaa-logo.png
  src/routes.js
Labels: enhancement

#1023 VAR-197 | Move HomePage to src, refactor without redux connect
  app/actions/purposeActions.js
  app/constants/ActionTypes.js
  app/pages/_pages.scss
  app/pages/home/HomePage.js
  app/pages/home/__tests__/HomePage.test.js
  app/pages/home/__tests__/homePageSelector.test.js
  app/pages/home/homePageSelector.js
  app/pages/reservation/reservation-time/ReservationTime.js
  app/pages/resource/resource-info/ResourceInfo.js
  app/state/reducers/api/__tests__/shouldFetchReducer.test.js
  app/state/reducers/api/shouldFetchReducer.js
  app/state/reducers/dataReducer.js
  app/state/selectors/__tests__/dataSelectors.test.js
  app/state/selectors/dataSelectors.js
  app/store/middleware/Schemas.js
  src/domain/_domain.scss
  src/domain/home/HomePage.js
  src/domain/home/HomeSearchBox.js
  src/domain/home/__tests__/HomePage.test.js
  src/domain/home/__tests__/HomeSearchBox.test.js
  src/domain/home/__tests__/__snapshots__/HomePage.test.js.snap
  src/domain/home/__tests__/__snapshots__/HomeSearchBox.test.js.snap
  src/domain/home/_home-page.scss
  src/domain/home/images/etusivu_tausta.jpg
  src/domain/home/images/frontpage_build.svg
  src/domain/home/images/frontpage_guidance.svg
  src/domain/home/images/frontpage_music.svg
  src/domain/home/images/frontpage_sport.svg
  src/domain/home/images/frontpage_work.svg
  src/routes.js
Labels: enhancement

#1024 VAR-190 | Disable Reserve button when user is not logged in
  app/pages/resource/ResourcePage.js
  src/domain/resource/reservationCalendar/ResourceReservationCalendar.js
Labels: enhancement

#1027 VAR-190 | Improve resource page usability for anonymous users
  CHANGELOG.md
  app/i18n/messages/en.json
  app/i18n/messages/fi.json
  app/i18n/messages/sv.json
  src/common/calendar/__tests__/TimePickerCalendar.test.js
  src/domain/resource/reservationCalendar/ResourceReservationCalendar.js
  src/domain/resource/reservationCalendar/__tests__/__snapshots__/ResourceReservationCalendar.test.js.snap
  src/domain/resource/reservationCalendar/_resourceReservationCalendar.scss
Labels: enhancement

#1026 VAR-182 | FullCalendar minPeriod
  CHANGELOG.md
  app/constants/AppConstants.js
  app/pages/AppContainer.js
  app/pages/__tests__/AppContainer.test.js
  app/pages/reservation/ReservationPage.js
  app/pages/reservation/reservation-time/ReservationTime.js
  app/pages/reservation/reservation-time/__tests__/ReservationTime.test.js
  app/state/reducers/__tests__/notificationsReducer.test.js
  app/state/reducers/notificationsReducer.js
  src/common/calendar/TimePickerCalendar.js
  src/common/calendar/__tests__/TimePickerCalendar.test.js
  src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap
  src/common/calendar/utils.js
  src/common/notification/constants.js
  src/common/notification/utils.js
  src/domain/resource/__tests__/utils.test.js
  src/domain/resource/reservationCalendar/ResourceReservationCalendar.js
  src/domain/resource/utils.js
Labels: enhancement
